development:
  adapter: postgresql
  encoding: unicode
  database: proficiency_test_development
  pool: 5
  username: postgres
  password: julinha

test:
  adapter: postgresql
  encoding: unicode
  database: proficiency_test_test
  pool: 5
  username: postgres
  password: julinha